[tool.commitizen]
changelog_merge_prerelease = true
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver2"
version = "1.19.4"
bump_message = "chore(release): v$new_version"
version_files = [
    "VERSION"
]
